###  <font color=[TPL_STATUS_COLOR]> [TPL_REPO_SHORT_NAME] build [TPL_STATUS_COLOR] [TPL_BUILD_STATUS] (`takes [TPL_BUILD_CONSUMING]s`) </font>

![]([TPL_STATUS_PIC] 50x50)

Message: [TPL_COMMIT_MSG]

Detail: [[TPL_COMMIT_SHA]]([TPL_COMMIT_LINK])

Author: [[TPL_AUTHOR_NAME]([TPL_AUTHOR_EMAIL])](mailto:[TPL_AUTHOR_EMAIL])

[Click To The Build Detail Page [TPL_STATUS_EMOTICON]]([TPL_BUILD_LINK])
